# evaluate I8_nl0
device: auto
model:
  ckpt_path: ckpt/baseline/dnn_ae.pt
data:
  X: data/baseline/ae/eval/I8/n0/X_I8_nl0.pt
  y: data/baseline/ae/eval/I8/n0/y_I8_nl0.pt
  batch_size: 128
out:
  dir: eval/baseline/ae/I8/n0
  num_classes: 4
  target_names: ["Normal", "Location1", "Location2", "Location3"]
  cm_title: "AE — Severity=2, Noise=0%"
