# evaluate I8_nl50
device: auto
model:
  ckpt_path: ckpt/baseline/vae_transformer_clf.pt
data:
  X: data/baseline/transformer/eval/I8/n50/X_I8_nl50.pt
  y: data/baseline/transformer/eval/I8/n50/y_I8_nl50.pt
  batch_size: 128
out:
  dir: eval/baseline/transformer/I8/n50
  num_classes: 4
  target_names: ["Normal", "Location1", "Location2", "Location3"]
  cm_title: "VAE+Transformer — Severity=2, Noise=50%"
