# evaluate I6_nl0
device: auto
model:
  ckpt_path: ckpt/baseline/vae_transformer_clf.pt
data:
  X: data/baseline/transformer/eval/I6/n0/X_I6_nl0.pt
  y: data/baseline/transformer/eval/I6/n0/y_I6_nl0.pt
  batch_size: 128
out:
  dir: eval/baseline/transformer/I6/n0
  num_classes: 4
  target_names: ["Normal", "Location1", "Location2", "Location3"]
  cm_title: "VAE+Transformer — Severity=4, Noise=0%"
