# evaluate I5_nl10
device: auto
model:
  ckpt_path: ckpt/baseline/vae_rnn_clf.pt
data:
  X: data/baseline/vae_rnn/eval/I5/n10/X_I5_nl10.pt
  y: data/baseline/vae_rnn/eval/I5/n10/y_I5_nl10.pt
  batch_size: 128
out:
  dir: eval/baseline/vae_rnn/I5/n10
  num_classes: 4
  target_names: ["Normal", "Location1", "Location2", "Location3"]
  cm_title: "VAE+RNN — Severity=5, Noise=10%"
